### ISSUE TITLE
feature中的一些函数好像并没有用到

### ISSUE THREAD

**Issue by JohnComeon** [LogicJake/2020-yizhifu-credit-risk-user-identification-Top2#3]
例如select——feature、w2v_emb、tfidf_emb等函数好像没有再使用过，请问作者这是什么原因？
`def select_feature(df, select_feature, ycol, p):
    X = df[select_feature]
    X.fillna(0, inplace=True)
    Y = df[ycol]

    selectChi2 = SelectPercentile(chi2, percentile=p).fit(X, Y)
    selectF_classif = SelectPercentile(f_classif, percentile=p).fit(X, Y)

    chi2_selected = selectChi2.get_support()
    print('Chi2 selected {} features.'.format(chi2_selected.sum()))
    f_classif_selected = selectF_classif.get_support()
    print('F_classif selected {} features.'.format(f_classif_selected.sum()))
    selected = chi2_selected & f_classif_selected
    print('Chi2 & F_classif selected {} features'.format(selected.sum()))
    selected_features = [f for f, s in zip(select_feature, selected) if s]

    del_features = list(set(select_feature) - set(selected_features))
    del_features.sort()
    return del_features`

**Comment by LogicJake** [comment]
都是尝试过没有提升的方法

**Comment by JohnComeon** [comment]
> 都是尝试过没有提升的方法

好的，谢谢了
